package it.tabacchi.enums;

public enum Categoria {

    SIGARETTE, SIGARI, SIGARELLI, TABACCO_SENZA_COMBUSTIONE, ALTRI_TABACCHI_DA_FUMO,
    DISPOSITIVI_ELETTRONICI_E_ALTRI_PRODOTTI, FIUTI_E_MASTICO, NICOTINE_POUCHES,
    SIGARETTE_ELETTRONICHE_RICARICABILI_E_RICARICHE, TRINCIATI_PER_SIGARETTE, 


}
